CXX  = g++.exe
WINDRES = windres.exe
RM = rm -f

INCDIR = C:/Dev-Cpp/include
SRCDIR = ..
RCDIR = .
OBJDIR = ../obj
BINDIR = ../..

FILES = Constants Settings Levelset SDL_util
DFILES = DiamondsApp DiamondsFrame SDLPanel SDLSound Ball Field HiScore Globals
EFILES = EditorApp EditorFrame

OBJ = $(addsuffix .o, $(addprefix $(OBJDIR)/, $(FILES)))
DOBJ = $(addsuffix .o, $(addprefix $(OBJDIR)/, $(DFILES)))
EOBJ = $(addsuffix .o, $(addprefix $(OBJDIR)/, $(EFILES)))

DRC = $(RCDIR)/Diamonds_private.rc
ERC = $(RCDIR)/Editor_private.rc

DRES = $(OBJDIR)/Diamonds_private.res
ERES = $(OBJDIR)/Editor_private.res

DBIN = $(BINDIR)/diamonds.exe
EBIN = $(BINDIR)/editor.exe

LIBS = -L"lib" -mwindows -lmingw32 -lSDLmain -lSDL -lSDL_image -lSDL_mixer \
       -lSDL_ttf -lwxmsw28_core -lwxbase28 -lcomdlg32 -luser32 -lgdi32 \
       -lole32 -lwsock32 -lcomctl32 -lctl3d32 -lgcc -lstdc++ -lshell32 \
       -loleaut32 -ladvapi32 -luuid
CXXINCS = -I$(INCDIR)/c++/3.4.5/mingw32 -I$(INCDIR)/c++/3.4.5 \
          -I$(INCDIR)/SDL  -I"include"
CXXFLAGS = $(CXXINCS) -c -Wall

.PHONY: all clean diamonds editor

all: diamonds editor

diamonds: $(DBIN)

editor: $(EBIN)

clean:
	$(RM) $(OBJ) $(DOBJ) $(EOBJ) $(DRES) $(ERES) $(DBIN) $(EBIN)

$(DBIN): $(OBJ) $(DOBJ) $(DRES)
	$(CXX) $(OBJ) $(DOBJ) $(DRES) -o $(DBIN) $(LIBS) -s

$(EBIN): $(OBJ) $(EOBJ) $(ERES)
	$(CXX) $(OBJ) $(EOBJ) $(ERES) -o $(EBIN) $(LIBS) -s

$(OBJDIR)/%.o : $(SRCDIR)/%.cpp
	$(CXX) $(CXXFLAGS) $< -o $@

$(OBJDIR)/%.res : $(RCDIR)/%.rc
	$(WINDRES) -i $< --input-format=rc -o $@ -O coff

